pipeline{
  agent any
  stages{
    stage("CI"){
      steps{
        script{
          example()
        }
      }
    }

    stage("Deneme"){
      steps{
        script{
          print "Emin"
        }
      }
    }

    stage("Deneme-2"){
      steps{
        script{
          print "Turan"
        }
      }
    }
  }
}
